### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by Vasyl-Poremchuk**

### CODE REVIEW

**Comment by Vasyl-Poremchuk** [comment]
image

**Comment by Vasyl-Poremchuk** [comment]
image

**Comment by Vasyl-Poremchuk** [comment]
image

**Comment by Vasyl-Poremchuk** [comment]
image

**Comment by Vasyl-Poremchuk** [comment]
image

**Review by Gr1zzZzzly — APPROVED** [review]

**Review by Y-Havryliv — APPROVED** [review]
Well done!

**Pull request closed without merging**
