### PR TITLE
added students checklist

### PR DESCRIPTION
**Pull request by Nattalli**

### CODE REVIEW

**Review by DmytroSvirsa — CHANGES_REQUESTED** [review]
for checklist:
image
image

**Review by Abnormaltype — CHANGES_REQUESTED** [review]
also, add this point:
please, add a blank for the end of the file

**Comment by Nattalli** [comment]
> also, add this point: please, add a blank for the end of the file

I added it in the end of the 8th item

**Comment by Nattalli** [comment]
> for checklist: image image

This point was there before, but I will add a little text here
Снимок экрана 2022-11-01 в 11 55 12

**Review by Abnormaltype — APPROVED** [review]
LGTM

**Review by DmytroSvirsa — APPROVED** [review]

**Pull request merged**
