### PR TITLE
Pythons

### PR DESCRIPTION
**Pull request by InnaKushnir**

### CODE REVIEW

**Comment by InnaKushnir** [comment]
I installed toolbar in this project, and did not use it. I have problem with it now. How can it be solved?

**Comment by InnaKushnir** [comment]
image

**Comment by InnaKushnir** [comment]
image

**Comment by InnaKushnir** [comment]
image

**Comment by InnaKushnir** [comment]
image

**Review by Abnormaltype — CHANGES_REQUESTED** [review]
gave you comments in the slack

**Comment by InnaKushnir** [comment]
I can't delete any files now, I need them all

**Review by Abnormaltype — CHANGES_REQUESTED** [review]
you should only delete it from the pr)

**Comment by InnaKushnir** [comment]
delete it from commit?

**Pull request closed without merging**
